In [1]:
# import libraries
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [2]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        #X_train, X_test, y_train, y_test = train_test_split(indep_X,dep_Y, test_size = 0.25, random_state = 0)
        
        #Feature Scaling
        #from sklearn.preprocessing import StandardScaler
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test

In [3]:
def r2_prediction(regressor,X_test,y_test):
     y_pred = regressor.predict(X_test)
     from sklearn.metrics import r2_score
     r2=r2_score(y_test,y_pred)
     return r2

In [4]:
def Linear(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LinearRegression
        regressor = LinearRegression()
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [5]:
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'linear')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [6]:
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'rbf')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [7]:
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training setC
        from sklearn.tree import DecisionTreeRegressor
        regressor = DecisionTreeRegressor(random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [8]:
def random(X_train,y_train,X_test):
    
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestRegressor
        regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [16]:
    
def rfeFeature(indep_X,dep_Y,n):
        rfelist=[]
        
        from sklearn.linear_model import LinearRegression
        lin = LinearRegression()
        
        from sklearn.svm import SVR
        SVRl = SVR(kernel = 'linear')
        
        from sklearn.svm import SVR
        #SVRnl = SVR(kernel = 'rbf')
        
        from sklearn.tree import DecisionTreeRegressor
        dec = DecisionTreeRegressor(random_state = 0)
        
        from sklearn.ensemble import RandomForestRegressor
        rf = RandomForestRegressor(n_estimators = 10, random_state = 0)       
        
        rfemodellist=[lin,SVRl,dec,rf] 
        for i in   rfemodellist:
            print(i)
            log_rfe = RFE(estimator=i, n_features_to_select=n)
            log_fit = log_rfe.fit(indep_X, dep_Y)
            log_rfe_feature=log_fit.transform(indep_X)
            rfelist.append(log_rfe_feature)
        return rfelist

In [17]:
def rfe_regression(acclog,accsvml,accdes,accrf): 
    
    rfedataframe=pd.DataFrame(index=['Linear','SVC','Random','DecisionTree'],columns=['Linear','SVMl',
                                                                                        'Decision','Random'])

    for number,idex in enumerate(rfedataframe.index):
        
        rfedataframe['Linear'][idex]=acclog[number]       
        rfedataframe['SVMl'][idex]=accsvml[number]
        rfedataframe['Decision'][idex]=accdes[number]
        rfedataframe['Random'][idex]=accrf[number]
    return rfedataframe

In [18]:
dataset1=pd.read_csv("prep.csv",index_col=None)

In [19]:
df2=dataset1.copy()
df2 = pd.get_dummies(df2, drop_first=True, dtype=int)

In [20]:
indep_X=df2.drop('classification_yes', axis=1)
dep_Y=df2['classification_yes']

In [21]:
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [51]:
rfelist=rfeFeature(indep_X,dep_Y,14)       

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

LinearRegression()
SVR(kernel='linear')
DecisionTreeRegressor(random_state=0)
RandomForestRegressor(n_estimators=10, random_state=0)

In [52]:
rfelist

[array([[ 3.        , 12.51815562,  0.        , ...,  0.        ,
          1.        ,  0.        ],
        [ 2.        , 10.7       ,  0.        , ...,  0.        ,
          1.        ,  0.        ],
        [ 1.        , 12.        ,  0.        , ...,  0.        ,
          1.        ,  0.        ],
        ...,
        [ 3.        ,  9.1       ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  8.5       ,  0.        , ...,  0.        ,
          1.        ,  1.        ],
        [ 0.        , 16.3       ,  0.        , ...,  0.        ,
          1.        ,  0.        ]]),
 array([[ 3.        ,  0.        , 12.51815562, ...,  0.        ,
          1.        ,  0.        ],
        [ 2.        ,  0.        , 10.7       , ...,  0.        ,
          1.        ,  0.        ],
        [ 1.        ,  0.        , 12.        , ...,  0.        ,
          1.        ,  0.        ],
        ...,
        [ 3.        ,  0.        ,  9.1       , ...,  1.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  8.5       , ...,  1.        ,
          1.        ,  1.        ],
        [ 0.        ,  0.        , 16.3       , ...,  0.        ,
          1.        ,  0.        ]]),
 array([[ 57.48210526,   3.07735602,  12.51815562, ...,   0.        ,
           0.        ,   0.        ],
        [ 22.        ,   0.7       ,  10.7       , ...,   0.        ,
           0.        ,   0.        ],
        [ 23.        ,   0.6       ,  12.        , ...,   0.        ,
           0.        ,   0.        ],
        ...,
        [115.        ,   6.        ,   9.1       , ...,   0.        ,
           0.        ,   1.        ],
        [ 80.        ,   6.8       ,   8.5       , ...,   0.        ,
           0.        ,   1.        ],
        [ 49.        ,   1.        ,  16.3       , ...,   0.        ,
           0.        ,   0.        ]]),
 array([[  3.        , 148.11267606,  57.48210526, ...,   0.        ,
           0.        ,   0.        ],
        [  2.        , 148.11267606,  22.        , ...,   1.        ,
           0.        ,   0.        ],
        [  1.        ,  99.        ,  23.        , ...,   1.        ,
           0.        ,   0.        ],
        ...,
        [  3.        , 110.        , 115.        , ...,   1.        ,
           1.        ,   1.        ],
        [  0.        , 207.        ,  80.        , ...,   1.        ,
           1.        ,   1.        ],
        [  0.        , 100.        ,  49.        , ...,   1.        ,
           0.        ,   0.        ]])]

In [53]:
for i in rfelist:   
    X_train, X_test, y_train, y_test=split_scalar(i,dep_Y)  
    r2_lin=Linear(X_train,y_train,X_test)
    acclin.append(r2_lin)
    
    r2_sl=svm_linear(X_train,y_train,X_test)    
    accsvml.append(r2_sl)
    
    r2_NL=svm_NL(X_train,y_train,X_test)
    accsvmnl.append(r2_NL)
    
    r2_d=Decision(X_train,y_train,X_test)
    accdes.append(r2_d)
    
    r2_r=random(X_train,y_train,X_test)
    accrf.append(r2_r)

In [54]:
result=rfe_regression(acclin,accsvml,accdes,accrf)

In [55]:
import warnings
warnings.filterwarnings("ignore")

In [50]:
result
#8

                Linear      SVMl  Decision    Random
Linear        0.709204  0.684292  0.952168  0.932773
SVC           0.701052  0.679964   0.82978  0.922139
Random        0.703917  0.673437  0.782986  0.918403
DecisionTree  0.712812  0.671713  0.913194  0.945312

In [44]:
result
#12

                Linear      SVMl  Decision    Random
Linear        0.710168  0.678884  0.968654  0.954369
SVC           0.707897  0.685439  0.968654  0.955046
Random        0.689882  0.656671  0.826389  0.927083
DecisionTree  0.644101  0.579452  0.826389  0.882378

In [57]:
result
#14

                Linear      SVMl  Decision    Random
Linear        0.709491  0.675038  0.998794  0.973136
SVC           0.708906  0.667743  0.998794  0.978539
Random        0.699524  0.665739  0.782986  0.907552
DecisionTree  0.651817  0.577015  0.696181  0.888889